import { useState, useCallback } from 'react';
import type { McpProject, Endpoint, AuthConfig, MethodPermissions } from './types';
import { DEFAULT_AUTH, DEFAULT_PERMISSIONS, createEndpoint } from './types';
import Layout from './components/Layout';
import ServerConfig from './components/ServerConfig';
import AuthConfigPanel from './components/AuthConfig';
import EndpointList from './components/EndpointList';
import EndpointEditor from './components/EndpointEditor';
import PermissionsPanel from './components/PermissionsPanel';
import ImportModal from './components/ImportModal';
import AnalysisPanel from './components/AnalysisPanel';
import CodePreview from './components/CodePreview';
import DownloadPanel from './components/DownloadPanel';

type Tab = 'endpoints' | 'analysis' | 'generate';

export default function App() {
  const [project, setProject] = useState<McpProject>({
    name: 'my-api-mcp-server',
    description: 'MCP server generated by MCP Forge',
    version: '1.0.0',
    baseUrl: '',
    auth: DEFAULT_AUTH,
    endpoints: [],
    permissions: DEFAULT_PERMISSIONS,
  });

  const [selectedEndpointId, setSelectedEndpointId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<Tab>('endpoints');
  const [showImport, setShowImport] = useState(false);

  const selectedEndpoint = project.endpoints.find((e) => e.id === selectedEndpointId) || null;

  const updateProject = useCallback((updates: Partial<McpProject>) => {
    setProject((prev) => ({ ...prev, ...updates }));
  }, []);

  const updateAuth = useCallback((auth: AuthConfig) => {
    setProject((prev) => ({ ...prev, auth }));
  }, []);

  const updatePermissions = useCallback((permissions: MethodPermissions) => {
    setProject((prev) => ({ ...prev, permissions }));
  }, []);

  const addEndpoint = useCallback(() => {
    const ep = createEndpoint();
    setProject((prev) => ({ ...prev, endpoints: [...prev.endpoints, ep] }));
    setSelectedEndpointId(ep.id);
  }, []);

  const updateEndpoint = useCallback((updated: Endpoint) => {
    setProject((prev) => ({
      ...prev,
      endpoints: prev.endpoints.map((e) => (e.id === updated.id ? updated : e)),
    }));
  }, []);

  const deleteEndpoint = useCallback((id: string) => {
    setProject((prev) => ({
      ...prev,
      endpoints: prev.endpoints.filter((e) => e.id !== id),
    }));
    if (selectedEndpointId === id) setSelectedEndpointId(null);
  }, [selectedEndpointId]);

  const duplicateEndpoint = useCallback((id: string) => {
    setProject((prev) => {
      const source = prev.endpoints.find((e) => e.id === id);
      if (!source) return prev;
      const dup = createEndpoint({ ...source, toolName: source.toolName + '_copy' });
      return { ...prev, endpoints: [...prev.endpoints, dup] };
    });
  }, []);

  const importEndpoints = useCallback((endpoints: Endpoint[], baseUrl?: string) => {
    setProject((prev) => ({
      ...prev,
      endpoints: [...prev.endpoints, ...endpoints],
      ...(baseUrl ? { baseUrl } : {}),
    }));
    setShowImport(false);
  }, []);

  return (
    <Layout>
      <div className="flex flex-col h-full">
        {/* Top bar: Server Config + Auth */}
        <div className="border-b border-gray-800 bg-gray-900/50">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 p-4">
            <ServerConfig
              name={project.name}
              description={project.description}
              version={project.version}
              baseUrl={project.baseUrl}
              onChange={(updates) => updateProject(updates)}
            />
            <AuthConfigPanel auth={project.auth} onChange={updateAuth} />
          </div>
        </div>

        {/* Tab bar */}
        <div className="flex items-center gap-1 px-4 pt-3 border-b border-gray-800">
          {([
            ['endpoints', 'Endpoints'],
            ['analysis', 'Analysis'],
            ['generate', 'Generate'],
          ] as [Tab, string][]).map(([tab, label]) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 text-sm font-medium rounded-t-lg transition-colors ${
                activeTab === tab
                  ? 'bg-gray-800 text-white border border-gray-700 border-b-gray-800 -mb-px'
                  : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
              }`}
            >
              {label}
            </button>
          ))}
          <div className="flex-1" />
          <button
            onClick={() => setShowImport(true)}
            className="px-3 py-1.5 text-sm bg-forge-600 hover:bg-forge-700 text-white rounded-lg transition-colors mb-1"
          >
            Import
          </button>
        </div>

        {/* Main content */}
        <div className="flex-1 overflow-hidden">
          {activeTab === 'endpoints' && (
            <div className="flex h-full">
              {/* Left: endpoint list */}
              <div className="w-80 border-r border-gray-800 flex flex-col">
                <EndpointList
                  endpoints={project.endpoints}
                  selectedId={selectedEndpointId}
                  permissions={project.permissions}
                  onSelect={setSelectedEndpointId}
                  onAdd={addEndpoint}
                  onDelete={deleteEndpoint}
                  onDuplicate={duplicateEndpoint}
                />
              </div>
              {/* Center: endpoint editor */}
              <div className="flex-1 overflow-auto">
                {selectedEndpoint ? (
                  <EndpointEditor
                    endpoint={selectedEndpoint}
                    baseUrl={project.baseUrl}
                    auth={project.auth}
                    onChange={updateEndpoint}
                  />
                ) : (
                  <div className="flex items-center justify-center h-full text-gray-500">
                    <div className="text-center">
                      <div className="text-5xl mb-4">&#9881;</div>
                      <p className="text-lg">Select an endpoint or add a new one</p>
                      <button
                        onClick={addEndpoint}
                        className="mt-4 px-4 py-2 bg-forge-600 hover:bg-forge-700 text-white rounded-lg transition-colors"
                      >
                        + Add Endpoint
                      </button>
                    </div>
                  </div>
                )}
              </div>
              {/* Right: permissions */}
              <div className="w-64 border-l border-gray-800">
                <PermissionsPanel
                  permissions={project.permissions}
                  onChange={updatePermissions}
                  endpointCounts={project.endpoints.reduce((acc, ep) => {
                    acc[ep.method] = (acc[ep.method] || 0) + 1;
                    return acc;
                  }, {} as Record<string, number>)}
                />
              </div>
            </div>
          )}

          {activeTab === 'analysis' && (
            <AnalysisPanel
              project={project}
              onUpdateEndpoint={updateEndpoint}
            />
          )}

          {activeTab === 'generate' && (
            <div className="grid grid-cols-1 lg:grid-cols-2 h-full">
              <CodePreview project={project} />
              <DownloadPanel project={project} />
            </div>
          )}
        </div>
      </div>

      {showImport && (
        <ImportModal
          onImport={importEndpoints}
          onClose={() => setShowImport(false)}
        />
      )}
    </Layout>
  );
}
